# mec-attendence-parser
A simple java application to retrieve attendance of a student

The program performs a query on http://www.mec.ac.in/attn/view4stud.php with post variable as the student's class and collects the response web page generated by the server. It then parses through the response and filters out the attendence of the required student. The result is displayed on the terminal for now, can be extended to be used in android projects or with other platforms.
